/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CampaignList__factory } from "./CampaignList__factory";
export { ICampaignList__factory } from "./ICampaignList__factory";
