/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  AppStorageInit,
  AppStorageInitInterface,
} from "../../../contracts/storage/AppStorageInit";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "heritageToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "protocolFeeBasePercentage",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gracePeriod",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expirationThreshold",
        type: "uint256",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x6080806040523461005b5760008054336001600160a01b0319821681178355916001600160a01b03909116907f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e09080a361027890816100618239f35b600080fdfe6080604052600436101561001257600080fd5b6000803560e01c8063715018a6146101905780638da5cb5b1461016957806398c36c09146101125763f2fde38b1461004957600080fd5b3461010f57602036600319011261010f576004356001600160a01b038181169182900361010b576100786101ea565b81156100b75782546001600160a01b0319811683178455167f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e08380a380f35b60405162461bcd60e51b815260206004820152602660248201527f4f776e61626c653a206e6577206f776e657220697320746865207a65726f206160448201526564647265737360d01b6064820152608490fd5b8280fd5b80fd5b503461010f57608036600319011261010f576004356001600160a01b03811690819003610165576101416101ea565b81546001600160a01b03191617815560243560015560443560035560643560045580f35b5080fd5b503461010f578060031936011261010f57546040516001600160a01b039091168152602090f35b503461010f578060031936011261010f576101a96101ea565b80546001600160a01b03198116825581906001600160a01b03167f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e08280a380f35b6000546001600160a01b031633036101fe57565b606460405162461bcd60e51b815260206004820152602060248201527f4f776e61626c653a2063616c6c6572206973206e6f7420746865206f776e65726044820152fdfea264697066735822122014c62c2191fb85e272178c18058f5364dadcb8f190ab863cca65dd67953eefa564736f6c63430008110033";

type AppStorageInitConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AppStorageInitConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AppStorageInit__factory extends ContractFactory {
  constructor(...args: AppStorageInitConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<AppStorageInit> {
    return super.deploy(overrides || {}) as Promise<AppStorageInit>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AppStorageInit {
    return super.attach(address) as AppStorageInit;
  }
  override connect(signer: Signer): AppStorageInit__factory {
    return super.connect(signer) as AppStorageInit__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AppStorageInitInterface {
    return new utils.Interface(_abi) as AppStorageInitInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AppStorageInit {
    return new Contract(address, _abi, signerOrProvider) as AppStorageInit;
  }
}
