/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as cloneable from "./Cloneable";
export * as tokenMinterFactoryCloneSol from "./TokenMinterFactoryClone.sol";
export { BurnMintable__factory } from "./BurnMintable__factory";
export { SimpleERC20__factory } from "./SimpleERC20__factory";
export { StandardERC20__factory } from "./StandardERC20__factory";
export { TokenMinter__factory } from "./TokenMinter__factory";
export { TokenMinterFactory__factory } from "./TokenMinterFactory__factory";
