/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as burnMintableSol from "./BurnMintable.sol";
export * as simpleErc20Sol from "./SimpleERC20.sol";
export * as standardErc20Sol from "./StandardERC20.sol";
