/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./Mocks";
export type { mocks };
export type { Lock } from "./Lock";
export type { NFTToken } from "./NFTToken";
export type { Token } from "./Token";
export type { ZLend } from "./ZLend";
export type { ZLend2 } from "./ZLend2";
export type { ZLendToken } from "./ZLendToken";
