/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface TestInterface extends utils.Interface {
  functions: {
    "bytesToBytes32Array(bytes)": FunctionFragment;
    "decodeArray(bytes)": FunctionFragment;
    "t()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "bytesToBytes32Array" | "decodeArray" | "t"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bytesToBytes32Array",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "decodeArray",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "t", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "bytesToBytes32Array",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodeArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "t", data: BytesLike): Result;

  events: {};
}

export interface Test extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bytesToBytes32Array(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    decodeArray(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string[]] & { result: string[] }>;

    t(overrides?: CallOverrides): Promise<[string]>;
  };

  bytesToBytes32Array(
    data: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  decodeArray(
    data: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  t(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    bytesToBytes32Array(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    decodeArray(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    t(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    bytesToBytes32Array(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decodeArray(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    t(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    bytesToBytes32Array(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decodeArray(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    t(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
