/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Signatory__factory } from "./Signatory__factory";
export { Testator__factory } from "./Testator__factory";
