/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDexFactory__factory } from "./IDexFactory__factory";
export { IDexRouter__factory } from "./IDexRouter__factory";
